version: 1.0

# executors
executors:
  node:
    docker:
      - image: circleci/node:10.15.3
  node_browsers:
    docker:
      - image: circleci/node:10-browsers

jobs:
  deploy:
    executor: node
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints:
          - "ea:5f:17:60:91:4b:e5:42:19:10:33:c7:ad:a1:5b:b6"
      - run:
        name: Deploy ssh
        command: |
          ssh ewok@florianchiraux.fr 'cd /home/pi/fireowls/webapps/ROOT && git pull'

workflow:
    version: 2.1
    jobs:
        - deploy
        
