version: 2.1

# executors
executors:
  node:
    docker:
      - image: circleci/node:10.15.3
  node_browsers:
    docker:
      - image: circleci/node:10-browsers

jobs:
  deploy:
    executor: node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "2048 MD5:ea:5f:17:60:91:4b:e5:42:19:10:33:c7:ad:a1:5b:b6 ewok@raspberrypi (RSA)"
      - run:
          name: Deploy ssh
          command: |
              ssh -o 'StrictHostKeyChecking no' ewok@florianchiraux.fr 'cd /home/pi/fireowls/webapps/ROOT && git pull'

workflows:
    version: 2.1
    integration:
        jobs:
                - deploy
        
